on:
  workflow_dispatch:
    inputs:
      region:
        description: AWS Region to delete from
        required: true
        default: 'eu-west-3'

name: delete development

run-name: Delete development env by @${{ github.actor }}

jobs:
  delete:
    name: Delete development stack
    uses: ./.github/workflows/delete.yaml
    with:
      environment: development
      region: ${{ inputs.region }}
    secrets: inherit
