on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'eu-west-3'
      api_id:
        description: ARN of the API
        required: true

name: deploy staging

run-name: Deploy to staging env by @${{ github.actor }}

jobs:
  build:
    name: Build with NPM
    uses: ./.github/workflows/build.yaml
    with:
      environment: staging

  deploy:
    name: Deploy to AWS - staging
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: staging
      region: ${{ inputs.region }}
      api_id: ${{ inputs.api_id }}
    secrets: inherit
