on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'eu-west-3'
      ApiId:
        description: ARN of the API
        required: true

name: deploy production

run-name: Deploy to production env by @${{ github.actor }}

jobs:
  build:
    name: Build with NPM
    uses: ./.github/workflows/build.yaml
    with:
      environment: production

  deploy:
    name: Deploy to AWS - production
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: production
      region: ${{ inputs.region }}
      api_id: ${{ inputs.api_id }}
    secrets: inherit
