name: Deploy to AWS

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        type: string
      region:
        description: 'AWS Region to deploy to'
        required: true
        type: string
      api_id:
        description: ARN of the API
        required: true
        type: string

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    name: Deploy the structure on AWS
    runs-on: ubuntu-latest
    steps:
      - name: Cache artifacts
        uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: |
            template.cfn.json
            build
          key: ${{ runner.os }}-artifacts-${{ inputs.environment }}

      - name: Configure environment name
        id: env-name
        env:
          REPO: ${{ github.repository }}
        run: |
          ENVIRONMENT="Foacs-website-be-user"
          ENVIRONMENT="${ENVIRONMENT}-${{ inputs.environment }}"
          echo "Environment name: $ENVIRONMENT"
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

      - name: Set up AWS CLI
        run: |
          echo "----Get aws cli----"
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          echo "----Unzip----"
          unzip -q awscliv2.zip
          echo "----Install----"
          sudo ./aws/install --update 
          echo "----Check aws----"
          aws --version
          echo "----Configure----"
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ inputs.region }}

      - name: Upload CloudFormation template to S3
        run: |
          echo "----Sync template file to S3 bucket----"
          aws s3 mv ./template.cfn.json s3://${{ secrets.AWS_BUCKET_NAME }}/${{ inputs.environment }}/user/template.cfn.json

      - name: Upload Lambda artifact to S3
        run: |
          echo "----Sync artifacts file to S3 bucket----"
          aws s3 sync ./build/ s3://${{ secrets.AWS_BUCKET_NAME }}/${{ inputs.environment }}/user/artifacts/ --include "*.zip"

      - name: Deploy backend stack
        id: backend-stack
        run: >
          aws cloudformation create-stack 
          --stack-name ${{ steps.env-name.outputs.environment }}
          --template-url https://${{ secrets.AWS_BUCKET_NAME }}.s3.${{ inputs.region }}.amazonaws.com/${{ inputs.environment }}/user/template.cfn.json
          --parameters ParameterKey=Env,ParameterValue=${{ inputs.environment }} ParameterKey=api_id,ParameterValue=${{ inputs.api_iId }}
