on:
  workflow_dispatch:
    inputs:
      region:
        description: AWS Region to deploy to
        required: true
        default: 'eu-west-3'
        type: string
      api_id:
        description: ID of the API
        required: true
        type: string
      root_resource_id:
        description: ID of the root API resource
        required: true
        type: string

name: deploy development

run-name: Deploy to development env by @${{ github.actor }}

jobs:
  build:
    name: Build with NPM
    uses: ./.github/workflows/build.yaml
    with:
      environment: development

  deploy:
    name: Deploy to AWS - development
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: development
      region: ${{ inputs.region }}
      api_id: ${{ inputs.api_id }}
      root_resource_id: ${{ inputs.root_resource_id }}
    secrets: inherit
