name: Deploy to AWS

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        type: string
      region:
        description: 'AWS Region to deploy to'
        required: true
        type: string
      api_id:
        description: ID of the API
        required: true
        type: string
      root_resource_id:
        description: ID of the root API resource
        required: true
        type: string

jobs:
  setup_aws_cli:
    name: Set up AWS CLI
    runs-on: ubuntu-latest
    steps:
      - name: Cache AWS CLI
        id: cache-aws-cli
        uses: actions/cache@v3
        with:
          path: |
            awscliv2.zip
            aws
          key: ${{ runner.os }}-aws-cli

      - name: Download AWS CLI
        if: steps.cache-aws-cli.outputs.cache-hit != 'true'
        run: |
          echo "----Get aws cli----"
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          echo "----Unzip----"
          unzip -q awscliv2.zip

  deploy:
    environment: ${{ inputs.environment }}
    name: Deploy the structure on AWS
    runs-on: ubuntu-latest
    needs: setup_aws_cli
    steps:
      - name: Cache AWS CLI
        id: cache-aws-cli
        uses: actions/cache@v3
        with:
          path: |
            awscliv2.zip
            aws
          key: ${{ runner.os }}-aws-cli

      - name: Cache artifacts
        uses: actions/cache@v3
        with:
          path: |
            infrastructure
            build
          key: ${{ runner.os }}-artifacts-${{ inputs.environment }}-${{ github.sha }}

      - name: Install AWS CLI
        run: |
          echo "----Install----"
          sudo ./aws/install --update 
          echo "----Check aws----"
          aws --version

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ inputs.region }}

      - name: Configure environment name
        id: env-name
        env:
          REPO: ${{ github.repository }}
        run: |
          ENVIRONMENT="Foacs-website-be-user"
          ENVIRONMENT="${ENVIRONMENT}-${{ inputs.environment }}"
          echo "Environment name: $ENVIRONMENT"
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

      - name: Upload CloudFormation template to S3 (API)
        run: >
          aws s3 sync
          ./infrastructure/ 
          s3://${{ secrets.AWS_BUCKET_NAME }}/${{ inputs.environment }}/user/

      - name: Upload Lambda artifact to S3
        run: >
          aws s3 sync 
          ./build/ 
          s3://${{ secrets.AWS_BUCKET_NAME }}/${{ inputs.environment }}/user/artifacts/ 
          --include "*.zip"

      - name: verify template
        id: verify_template
        run: >
          aws cloudformation validate-template
          --template-url https://${{ secrets.AWS_BUCKET_NAME }}.s3.${{ inputs.region }}.amazonaws.com/${{ inputs.environment }}/user/foacs-be-user.cfn.yml

      - name: Deploy stack
        run: >
          if ! aws cloudformation describe-stacks 
          --stack-name ${{ steps.env-name.outputs.environment }}; then

          aws cloudformation create-stack 
          --stack-name ${{ steps.env-name.outputs.environment }}
          --template-url https://${{ secrets.AWS_BUCKET_NAME }}.s3.${{ inputs.region }}.amazonaws.com/${{ inputs.environment }}/user/foacs-be-user.cfn.yml
          --parameters ParameterKey=Env,ParameterValue=${{ inputs.environment }} ParameterKey=RestApiId,ParameterValue=${{ inputs.api_id }}  
          ParameterKey=RootResourceId,ParameterValue=${{ inputs.api_id }} ParameterKey=region,ParameterValue=${{ github.event.inputs.region }} 
          ParameterKey=ParameterName,ParameterValue=${{ secrets.AWS_BUCKET_NAME }}
          --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND

          else

          aws cloudformation update-stack
          --stack-name ${{ steps.env-name.outputs.environment }}
          --template-url https://${{ secrets.AWS_BUCKET_NAME }}.s3.${{ inputs.region }}.amazonaws.com/${{ inputs.environment }}/user/foacs-be-user.cfn.yml
          --parameters ParameterKey=Env,ParameterValue=${{ inputs.environment }} ParameterKey=ApiId,ParameterValue=${{ inputs.root_resource_id }}
          ParameterKey=RootResourceId,ParameterValue=${{ inputs.api_id }} ParameterKey=region,ParameterValue=${{ github.event.inputs.region }} 
          ParameterKey=ParameterName,ParameterValue=${{ secrets.AWS_BUCKET_NAME }}
          --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND

          fi

      - name: Delete template on fail
        if: failure() && steps.verify_template.outcome != 'success'
        run: >
          aws s3 rm
          s3://${{ secrets.AWS_BUCKET_NAME }}/${{ inputs.environment }}/user/template.cfn.json

      - name: Delete artifacts on fail
        if: failure() && steps.verify_template.outcome != 'success'
        run: >
          aws s3 rm
          s3://${{ secrets.AWS_BUCKET_NAME }}/${{ inputs.environment }}/user/artifacts/
          --recursive
