on:
  workflow_dispatch:
    inputs:
      region:
        description: AWS Region to deploy to
        required: true
        default: 'eu-west-3'
      api_id:
        description: ARN of the API
        required: true

name: deploy development

run-name: Deploy to development env by @${{ github.actor }}

env:
  ENV_NAME: development

jobs:
  build:
    name: Build with NPM
    uses: ./.github/workflows/build.yaml

  deploy:
    name: Deploy to AWS - development
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: development
      region: ${{ inputs.region }}
      api_id: ${{ inputs.api_id }}
    secrets: inherit
