on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to upload to'
        required: true
        default: 'eu-west-3'

name: upload testing

run-name: Upload to testing env by @${{ github.actor }}

jobs:
  build:
    name: Build with NPM
    uses: ./.github/workflows/build.yaml
    with:
      environment: testing

  deploy:
    name: Upload to AWS - testing
    needs: build
    uses: ./.github/workflows/upload.yaml
    with:
      environment: testing
      region: ${{ inputs.region }}
    secrets: inherit
